### ISSUE TITLE
Menu robi segfaulta

### ISSUE THREAD

**Issue by kasztan2** [kasztan2/statki#11]
Menu powoduje segfaulta, wg gdb chodzi o nieistniejące `_menu->_maxx` i `_menu->_maxy`. *Chociaż moim zdaniem wcześniej działało...*

**Comment by zqxc** [comment]
w ktorym momencie sie to dzieje, po zakonczeniu gry?

**Comment by kasztan2** [comment]
na samym początku, w funkcji `start`

**Comment by kasztan2** [comment]
wymaganie dodane do readme
