### ISSUE TITLE
Źle losuje planszę bota

### ISSUE THREAD

**Issue by kasztan2** [kasztan2/statki#9]
Albo jest pięć jednomasztowców, albo dwumasztowiec dotyka rogiem trójmasztowca:
![image](https://user-images.githubusercontent.com/21148090/213799730-d32bd850-2dcf-4b9d-b7cd-ba23407cb73f.png)  
**Uwaga:** nie wiem czy bug jeszcze występuje, bardzo możliwe, że nie, ale wypadałoby sprawdzić

**Comment by DominikSzczepaniak** [comment]
na 120 testach nie wywaliło ani razu błędem z stykaniem się rogami, nie sprawdzałem jednak ilości statków

**Comment by kasztan2** [comment]
To w takim razie zamykam, problem był z rogami
